[build]
target = "xtensa-esp32-none-elf"

[target.'cfg(target_arch = "xtensa")']
runner = "espflash flash --monitor --partition-table partitions.csv"
rustflags = [
  "-C", "link-arg=-Wl,-Tlinkall.x",
  "-C", "link-arg=-nostartfiles",
  "-C", "link-arg=-Wl,--allow-multiple-definition",
]

[env]
ESP_LOG = "info"

[unstable]
build-std = ["core", "alloc"]
